default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 123
  host: 127.0.0.1
  port: 3306
  pool: 5
  socket: /path/to/the/socket/mysql.sock


development:
  <<: *default
  database: tresciclaje_pro

test:
  <<: *default
  database: tresciclaje_test

production:
  <<: *default
  database: tresciclaje_pro
  
